########################################
# prompt global settings
########################################

# document link: https://starship.rs/ja-JP/config/#%E3%83%95%E3%82%9A%E3%83%AD%E3%83%B3%E3%83%95%E3%82%9A%E3%83%88
# format = "$all"
format = """
$username\
$hostname\
$shlvl\
$kubernetes\
$directory\
$docker_context\
$package\
$cmake\
$memory_usage\
$env_var\
$cmd_duration\
$custom\
$line_break\
$jobs\
$battery\
$time\
$status\n\
$git_branch\
$git_commit\
$git_state\
$git_status\n\
$character"""
add_newline = true

########################################
# prompt detail settings
########################################

[username]
disabled = true
show_always = true
style_user = "white bold"
style_root = "white bold"
# format = "user: [$user]($style) "

[directory]
truncation_length = 0
truncate_to_repo = false

## Git settings
[git_branch]
style = "bold purple"
symbol = "îœ¥"
format = "[$symbol $branch(:$remote_branch)]($style)"
truncation_length = 100  # no truncation
truncation_symbol = "..."

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
conflicted = "[â¯](dimmed white) [ï²… conflicted](italic yellow) "
ahead = "[â¯](dimmed white) [ï˜¾Ã—${count} ahead](italic yellow) "
behind = "[â¯](dimmed white) [ï˜»Ã—${count} behind](italic yellow) "
diverged = "[â¯](dimmed white) [ï‚ ï˜¾Ã—${ahead_count} ï˜»Ã—${behind_count} diverged](bold red) "
up_to_date = "[â¯](dimmed white) [ï¡” everything up-to-date!](italic green) "
untracked = "[â¯](dimmed white) [ï‹‹Ã—${count}](italic red) "
stashed = "[â¯](dimmed white) [ï¬’](yellow)"
modified = "[â¯](dimmed white) [ï€Ã—${count}](italic yellow) "
staged = "[â¯](dimmed white) [ï§Ã—${count}](italic green) "
renamed = "[â¯](dimmed white) [ïƒ¬Ã—${count}](italic yellow) "
deleted = "[â¯](dimmed white) [ï€”Ã—${count}](italic yellow) "
format = " $all_status$ahead_behind\n"

## Memory
[memory_usage]
disabled = false
symbol = "ï„‰"
format = "[â¯](bold red)[â¯](bold yellow)[â¯](bold green) [$symbol]($style) [${ram}( ~ ${swap})]($style) [â¯](dimmed white) "
threshold = 1
style = "bold dimmed white"

[jobs]
symbol = "ï¥­ "
threshold = 1

[battery]
disabled = false
full_symbol = "ï•¸ "
charging_symbol = "ï–ƒ "
discharging_symbol = "ï–‚ "
unknown_symbol = "ï•¾ "
empty_symbol = "ï•¹ "

[[battery.display]]
threshold = 20
style = "bold red"

[[battery.display]] 
threshold = 50
style = "bold yellow"

[[battery.display]]
threshold = 100
style = "bold green"

[time]
disabled = false
format = "[â¯](dimmed white) [ï³ $time]($style) "
style = "bold yellow"
use_12hr = false
time_format = "%a%e %b %T"
utc_time_offset = "+1"
time_range = "-"  # always: time_range="00:00:00-23:59:59"

[line_break]
disabled = true # separate prompt into 2 lines

[character]
disabled = false
success_symbol = "[ïš²](bold green)" 
error_symbol = "[ïš²](bold red) "

[docker_context]
disabled = false
symbol = "ğŸ³"
format = "[$symbol $context](blue bold)"
style = "blue bold"

[cmd_duration]
format = "[ï¨](bold cyan)[took $duration](bold cyan) [â¯](dimmed white) "
